### ISSUE TITLE
byro docker installation unrecoverably crashes after plugin installation (fints)

### ISSUE THREAD

**Issue by Nixbligger** [byro/byro#257] opened 2022-03-30 19:25 UTC
Hi there,

I was trying to setup byro to check it out as an option for the user and financial management of our little club supporting under-privileged children in Ethiopia.

With some fiddling and some minor issues I initially made it work via the docker compose pathway. Unfortunately, I began to install plugins to play around and extend functionality. With "[Gemeinnuetzigkeit](https://github.com/byro/byro-gemeinnuetzigkeit)" everything went well, but some updates to the python collection module made the [byro-fints plugin](https://github.com/henryk/byro-fints) fail and my byro installation ultimately crashed. 

Now I am unable to revert the fints installation and hoped to find some help regarding this. Btw., I have already opened a [respective issue](https://github.com/henryk/byro-fints/issues/2) at the fints plugin repo with some details, but there doesn't seem to be much activity lately.

Unfortunately, I am incapable to fix this issue with the plugin myself. Any idea how to get rid of it? 

Thx!

**Comment by rixx** [comment] 2022-03-30 19:57
Hard to say without seeing what you can do / have done, but you should be able to just `pip uninstall` the plugin. This is probably related/a duplicate of #255.

**Closed by rixx** 2022-03-30 19:57 UTC
